# Sprites communs aux pays fictifs.

lasermark:
	idle:
		Filename: fictifs|bits/lasermark.png

# Système pétrole (common/petrole.yaml).
pipeline:
	Defaults:
		Filename: fictifs|bits/pipeline.png
	idle:
		Length: 16
	damaged-idle:
		Start: 16
		Length: 16
	icon:
		Filename: fictifs|bits/pipelineicon.png

raffinerie.petrole:
	Defaults:
		Filename: fictifs|bits/raffinerie.petrole.png
	idle:
		Length: 4
		Tick: 160
	damaged-idle:
		Start: 4
		Length: 4
		Tick: 160
	make:
		Start: 8
		Length: 8
		Tick: 60
	icon:
		Filename: fictifs|bits/raffinerie.petroleicon.png

# Zone industrielle (common/zones.yaml).
zone.industrielle:
	idle:
		Filename: fictifs|bits/zone.industrielle.png
		Length: 4
		Tick: 200
